### ISSUE TITLE
[Suggestion] - Ability to fade away messages

### ISSUE THREAD

**Issue by JohnnyS** [Concept-Collective/cc-chat#1]
Wondering if its possible to be able to add the ability to fade away the message that show up in the chat. 

So it would fade away after x seconds

**Comment by 69u** [comment]
G'day @JohnnyS, This can easily be accomplished with JQuery's setTimeout() and fadeOut() methods.

I will discuss with @Jye-AU about implementing this into our script.

**Comment by JohnnyS** [comment]
> G'day @JohnnyS, This can easily be accomplished with JQuery's setTimeout() and fadeOut() methods.
> 
> I will discuss with @Jye-AU about implementing this into our script.

Thank you so much! Im loving the design
