### ISSUE TITLE
Announcement issue

### ISSUE THREAD

**Issue by D3lta-Byte** [Concept-Collective/cc-chat#10]
When i do like for example /clearall, the announcement stays on screen. does not go away.

is there a fix for this?

**Comment by Jye-AU** [comment]
Not really sure what you are talking about, could you please explain further and attach screenshots?

**Comment by Soldierofthelam** [comment]
Same issues only thing that works is /OCC non of the other commands work, /twt so forth
Also commands to clear chat non functional too and draw no errors 

https://youtu.be/4zkfghj0y88


![bandicam 2022-12-12 19-34-19-466](https://user-images.githubusercontent.com/117047687/207197477-a0e710e7-2153-4c86-a085-7cfc840f61d4.jpg)

**Comment by Soldierofthelam** [comment]
SO I've tested the updates and the only version I can get to work with the newest qbcore is cc-chat version '1.2.1'

**Comment by Jye-AU** [comment]
> commands

The YouTube video you attached dose not work

**Comment by Soldierofthelam** [comment]
> > commands
> 
> The YouTube video you attached dose not work

It was set to private I switched the video to unlisted I've got most of it to work on version build 1.2.1 but not everything,
Any higher build nothing at all seems to work but OOC texting which  the video was in build version 1.2.8

**Comment by 69u** [comment]
> > > commands
> > 
> > 
> > The YouTube video you attached dose not work
> 
> It was set to private I switched the video to unlisted I've got most of it to work on version build 1.2.1 but not everything, Any higher build nothing at all seems to work but OOC texting which the video was in build version 1.2.8

Hello, I would highly suggest using [CC-RPChat](https://github.com/Concept-Collective/cc-rpchat) as it is basically a template for CC Chat :)
