### ISSUE TITLE
Missing the black background in input box

### ISSUE THREAD

**Issue by ErwinAT** [Concept-Collective/cc-chat#12]
![image](https://user-images.githubusercontent.com/123399709/214101101-131f1166-54f0-406f-ab88-f34b48c97c13.png)

**Comment by 69u** [comment]
Hey there, Are you running the purely the default chat script. CC-Chat and CC-RPChat?

**Comment by Jye-AU** [comment]
Thank you for submitting an issue to our GitHub repository. However, we regret to inform you that we will be closing this issue as no reasons or further details were specified in your original submission.
