### ISSUE TITLE
[Suggestion] Ability to change name.

### ISSUE THREAD

**Issue by ivegotthis** [Concept-Collective/cc-chat#13]
Hi, i appreciate that in life servers your character has the correct name because you log characters in and out but for scenario based servers it would be great if this script would allow you to change your name and have it show in the chat box. Thanks

**Comment by Jye-AU** [comment]
Thank you for your suggestion regarding the ability to change player names in CC Chat.

After careful consideration, we have decided not to implement this feature in the core functionality of CC Chat. However, we understand that this feature can be useful for certain server types and scenarios.

Therefore, we suggest that server owners can implement this feature on their own by modifying the code and using plugins or scripts that allow players to change their names within the game. This approach would give server owners more control over the feature and enable them to tailor it to the specific needs of their server.

We appreciate your feedback and hope that this solution will meet your needs.

If you have any further questions or concerns, please feel free to reach out to us.
