### ISSUE TITLE
Any way to add discord logs

### ISSUE THREAD

**Issue by Capy1174** [Concept-Collective/cc-chat#3]
Any way to add discord logs for each and every type of command written 
Each command should have separate logs

**Comment by Jye-AU** [comment]
This suggestion is being taken into consideration.

**Comment by 69u** [comment]
I will implement an option to log all messages in the upcoming update, which will be released soon.

**Comment by NotReloads** [comment]
These loggings should be made with specific command configured in config, as RegisterKeyMappings would get spammed.

**Comment by 69u** [comment]
This has been added in the latest version of [CC-RPChat](https://github.com/Concept-Collective/cc-rpchat)
