### ISSUE TITLE
Need help with local OOC chat and ME and DO

### ISSUE THREAD

**Issue by Neznamycz** [Concept-Collective/cc-chat#7]
Hello, just downloaded this chat and i really love it. I added anonymous twitter, black market, ooc chat but these are showing to all players on the server so it was easy´. But how can i do local ooc chat so its showing to only near persons in chat? how to add /me and /do? Any help please?

**Comment by Jye-AU** [comment]
This feature has been added to CC RP Chat v1.2.2 it can be found here: https://github.com/Concept-Collective/cc-rpchat
